### ISSUE TITLE
hiding auto-generated CLI entries

### ISSUE THREAD

**Issue by dima1308** [clicon/clixon#153]
Hi @olofhagsand 
is it possible to hide some entries in the auto-generated CLI?

**Comment by olofhagsand** [comment]
That is a good question.
No, it is not currently implemente, since the auto-cli takes YANG and some options from clixon-config.yang as only input.
However, hide is a useful function as well as many other potential declarations that are somewhat more specific to the syntax.
I see it there are two ways to add this info (there may be more):
1) Add cli info in the YANG. 
2) Add them as annotations in a separate file or config.
I would prefer (2), such as adding api-paths annotations in clixon-config.yang or mayeb a separate clixon-cli.yang, eg: `/example:table/parameter=%s/password hide` or something.

**Comment by dima1308** [comment]
I also prefer (2).
Also, maybe it will be useful to implement a mechanism that will allow displaying starts for password parameters... And maybe the option to store passwords in a secure way in the DB (not as a clear text). What do you think?

**Comment by olofhagsand** [comment]
See the translate function, cligen tutorial Sec 3.13 for translating eg a password to an encrypted/hashed value.

**Comment by olofhagsand** [comment]
See https://github.com/clicon/clixon/issues/156
