### ISSUE TITLE
Can't use + symbol in the enum statement without quotes

### ISSUE THREAD

**Issue by vsharapov-udelphi** [clicon/clixon#241]
Hi Olof.
I need to use + symbol inside a enum assigned name.
With following declaration
            enum SFP+ {
                description
                  "SFP+";
            }
I see the error from clixon:
clixon_yang_parseerror: 349: Yang error: /usr/share/siklu@0.0.0//radio-bridge-tg-interfaces.yang on line 58: syntax error at or before: '+'
Declarations with quotes work well:
            enum 'SFP+' {
                description
                  "SFP+";
            }

As I understand http://www.yang-central.org/twiki/pub/Main/YangDocuments/rfc6020.html#enum quotes are optional. Also pyang even with --strict accept quotesless declaration.

**Comment by olofhagsand** [comment]
Yes, strings in clixon are too constrained wrt the RFC.
YANG tokenization as described in sec 6.1 means you can use quotes (double or single) everywhere including enum statement, which means you should be able to use both quoted and unquoted strings in this context.
The problem in clixon parser is it needs a rearrangement where the tokenization is made more formally in the scanner using yang-chars as described in (end of) section 14, RFC 7950.
Just fixing the + character is therefore complicated since it has a special meaning in the tokenization, ie "abc" + "def" and can only be done by some rearrangements of the scanner/parser.
But you can use it in quotes.

**Comment by olofhagsand** [comment]
+ added as legal char.
Still remains some differences wrt the RFC lexical string tokenization, but not applicable to this issue.
