### ISSUE TITLE
Conversion of ethernet address (PhysAddress) and IP address (IPAddress) crashes agent

### ISSUE THREAD

**Issue by shmuelhazan** [clicon/clixon#340]
Branch name: https://github.com/clicon/clixon/commit/a61567a916da2c58cc16a4d161238b8a7b1d9e3e

Configuring any leaf in clixon that represents a PhysAddress OID won't work and will crash snmpd / clixon_snmpd. From looking at the code, looks like xml to PhysAddress is not implemented; and IPAddress is not implemented in both ways (xml to smi, smi to xml)
I have a few reproductions, If you need more info, I will add more.

**Comment by olofhagsand** [comment]
@shmuelhazan Please tell me what is your expected behavior?
The type conversion SMI <--> YANG is complex for lack of good documentation (or maybe more accurately lack of understanding from my part)
In smidump:ed YANG, the type is  yang:phys-address which ultimately is resolved to a string:
```
     typedef phys-address {
       type string {
         pattern '([0-9a-fA-F]{2}(:[0-9a-fA-F]{2})*)?';
       }
```
In SMI, the type is:
```
PhysAddress ::= TEXTUAL-CONVENTION
    DISPLAY-HINT "1x:"
    STATUS       current
    DESCRIPTION
            "Represents media- or physical-level addresses."
    SYNTAX       OCTET STRING
```
Therefore, I translate it in the clicon_snmp to `ASN_OCTET_STR`.
If you have some input on how it usually is presented, eg via an snmpgetr output, please share.

**Comment by shmuelhazan** [comment]
Looks like this is the expected. snmpget shows PhyAddress as type STRING also with other network equipment (Tested on a random Netgear switch). Thanks for the quick fix.
