### ISSUE TITLE
Only getting the hardcoded state data values.

### ISSUE THREAD

**Issue by shubhtrix** [clicon/clixon#35]
Hi @olofhagsand !!!

I have two queries...
1.)
On doing a curl -G http://localhost/restconf/data, I'm only getting some hard coded values in `example_backend.c` from `example_statedata()` . I thing on curl it should get data from datastore and should also be able to manipulate the same. 
2.) 
Is it possible to run the command `curl -G http://localhost/restconf/data` from a remote host to get or post data. What should i need to change to achieve the same, current implementation is for local host.
 
With Regards,
Shubham

**Comment by olofhagsand** [comment]
1) curl -G should get both state and config data. Do you have config data? Otherwise add it with -X POST or the CLI. Example:
> curl -s -X GET http://localhost/restconf/data
{"data": {"interfaces-state": {"interface": [{"name": "eth0","type": "ex:eth","if-index": 42}]}}}
> curl -s -X POST http://localhost/restconf/data -d '{"interfaces":{"interface":{"name":"eth/0/0","type":"ex:eth","enabled":true}}}'
> curl -s -X GET http://localhost/restconf/data
{"data": {"interfaces": {"interface": [{"name": "eth/0/0","type": "ex:eth","enabled": true}]},"interfaces-state": {"interface": [{"name": "eth0","type": "ex:eth","if-index": 42}]}}}

2) Just change "localhost" to another host name or IP address.

**Comment by shubhtrix** [comment]
oh hi!!!

Yes!!! I tried with tests defined under test directory (perticularly restconf2.sh). Thanks for that. Trying to debug using it.
Will inform you after completing some of my personal test cases.

Regards,
Shubham
