### ISSUE TITLE
Issues with ietf-snmp modules

### ISSUE THREAD

**Issue by vvsosed** [clicon/clixon#353]
I use standard ietf-snmp yang models from [https://github.com/YangModels/yang/tree/main/standard/ietf/RFC](https://github.com/YangModels/yang/tree/main/standard/ietf/RFC). But in runtime logs I see

_Aug 16 10:00:48: Warning: Augment failed in module ietf-snmp-notification: node anydata 2 cannot be added to target node /snmp:snmp
Aug 16 10:00:48: Warning: Augment failed in module ietf-snmp-notification: node anydata 2 cannot be added to target node /snmp:snmp/snmp:target-params_

Looks like the yang parser can't parse ietf-snmp-notification submodule properly.

**Comment by olofhagsand** [comment]
Actually, the warning may be misleading but it is not an error.
The yang of one of the augment nodes is:
```
    list notify-filter-profile {
      if-feature snmp:notification-filter;
      key name;
```
and the snmp:notification-filter feature is disabled. Disabled nodes are transformed to ANYDATA nodes internally and since you cannot augment with ANYDATA, (see RFC 7950 Sec 7.17) it causes this warning message.
I will change the warning message to be more descriptive and also keep track of disabled + anydata nodes and ensure that no warning is printed in this case.

**Comment by olofhagsand** [comment]
Error message fixed and not printed in this case. Please verify.
