### ISSUE TITLE
Key of a list isn't mandatory

### ISSUE THREAD

**Issue by achernavin22** [clicon/clixon#73]
There is a data model:

```
  +--rw host-config
     +--rw security
        +--rw host-acls
           +--rw host-acl* [acl-name]
              +--rw acl-name       string
              +--rw acl-seq        uint32
              +--rw description?   string
```

If you PUT `/restconf/data/host-config` this via RESTCONF, it will be accepted:

```
{
    "host-config": {
        "security": {
            "host-acls": {
                "host-acl": [
                    {
                        "acl-seq": 0
                    }
                ]
            }
        }
    }
}
```

If you PUT `/restconf/data/host-config/security/host-acls/host-acl=` this via RESTCONF, there will be a segfault:

```
{
	"host-acl": {
		"acl-seq": 0,
		"acl-name": ""
	}
}
```

The `acl-seq` leaf is explicitly mandatory and it is validated correctly.

**Comment by olofhagsand** [comment]
Should be fixed now.
Thanks for reporting.
Problem here is that you can still add NULL keys via netconf - since validation is a separate step, but in cli or restconf it should not be possible.
This is the general problem of whether one should enforce all "must" constraints even before validation in candidate. I have chosen not to, but it can lead to some strange behaviour.
