### ISSUE TITLE
RESTCONF -Candidate Roll Back

### ISSUE THREAD

**Issue by sdj38** [clicon/clixon#9]
Hi Olof,

Doing some tests with POST and RESTCONF we found that if a commit does not validate against the backend it still gets stored in the candidate DB but not in the running DB. POST/DELETE/PUT should roll back the candidate DB if it does not validate. 

Here is output from /var/log/messages

`Jan 22 17:40:09 localhost clixon_backend[1335]: transaction_commit: 158: Config error: Invalid sw_if_index`
`Jan 22 17:40:09 localhost clixon_restconf[21077]: Commit failed. Edit and try again or discard changes: protocol invalid-value Invalid sw_if_index
`
This makes it so any HTTP request fails until the DB is cleared or fixed.

**Comment by olofhagsand** [comment]
Stephen,
Fixed by commit 6c7554de25ee0685dc542d8f616482b1dab8dd9a - rollback on commit errors in restconf
This error was triggered by an error in the commit rule. 
To be picky: it is better to make such checks in the validation callbacks.
I changed the restconf call so that errors in commit and in validate both rollback, not only validate.
