### ISSUE TITLE
Mode and context.

### ISSUE THREAD

**Issue by atoy40** [clicon/clixon#98]
Hello,

I'm new to CLixon and have a question. I want to write a CLI with submodes, for example to configure interface specific parameters (in this example, I use ietf interface yang module).

The main mode :
```
CLICON_MODE="main";
CLICON_PROMPT="%U@%H [config]# ";

interface("Exit configure mode") <interface:string>, cli_set_mode("interface");
```

The interface mode :
```
CLICON_MODE="interface";
CLICON_PROMPT="%U@%H [interface]# ";

exit("Exit interface mode"), cli_set_mode("main");

description("Description") <description:string>, cli_set("/ietf-interfaces:interfaces/interface=%s/description");
type("Interface type") <type:string>, cli_set("/ietf-interfaces:interfaces/interface=%s/type");
```

The problem is how can I "pass" the interface name (first variable of interface command) to the interface-specific CLI mode as ```cli_set("/ietf-interfaces:interfaces/interface=%s/type");``` need it to fill %s.
Do I need to write a new version of cli_set_mode() that store this context somewhere and a fork of cli_set() that use this state ? or is there any build in solution ?

thanks for help.

**Comment by olofhagsand** [comment]
Welcome!
You should be able to do this in several ways.
I personally usually do this by forming a single "interface" mode, and then store the interface name in the handle using the clixon_data API (eg see `clicon_username_get/set()`)
It is somewhat problematic doing a separate mode for each interface, since current code creates modes at initialization (declaratively), and for that to work, modes need to come and go dynamically. I know others have done this dynamically, but I don't know exactly how.
The way I would do it would be to append a new function which you declare, eg `cli_set_mode("interface"), store_interface()` where you pick up the argument something like this and store it (sorry sloppy code):
```
int
store_mode(clicon_handle h, 
	   cvec         *vars, 
	   cvec         *argv)
{
    clicon_hash_t  *cdat = clicon_data(h);
    cg_var         *cv1 = cvec_i(vars, 1);
    char           *name = cv_string_get(cv1);
    
    clicon_hash_add(cdat, "interfacename", name, strlen(name)+1);
    return 0;
}
```
However, I see this is a sufficiently important use-case, (many have it) so it should really have some documented lib support, but I have not come around doing it. 
I would appreciate help w adding this as a lib?

**Comment by NavaneethBhat** [comment]
Hi @olofhagsand I had a question on modes. I thought I will add it here as the subject pertains to modes. 

Does CLIXON automatically generate CLIs for a list / container as a new mode or does it always attach it to @datamodel tree ?

I will give an example.
Consider the following yang model.

`container ribs {
  status obsolete;
  description
    "Container for RIBs.";
  list rib {
    key "name";
    min-elements 1;
    status obsolete;
    leaf name {
      type string;
      status obsolete;
      description
        "The name of the RIB.";
`
Generated CLI is some what  `set ribs rib name my-rib-name`

My question is can this be generated as 

edit ribs
 >> edit rib
    >> set name my-rib-name

**Comment by olofhagsand** [comment]
Sorry missed this: 
No, the generated CLI does not generate automatic sub-modes in this way.
I relabel this to a possible enhancement of the auto-cli.

**Comment by NavaneethBhat** [comment]
Thank you !

**Comment by olofhagsand** [comment]
There is now auto-modes support since 4.8, see https://github.com/clicon/clixon/blob/master/CHANGELOG.md#480
